### ISSUE TITLE
Make frontend prototype

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#11]

**Comment by chemeshuggah** [comment]
https://docs.google.com/drawings/d/1P-h5IiIxSucx8YNn2PX7_d0BMDHF-npX8OJX-ZlBv8c/edit?usp=sharing

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah we need call for discuss this picture

**Comment by chemeshuggah** [comment]
Ok. I will be available today around 19-20 o'clock or earlier if you will be in town :)
