### ISSUE TITLE
add endpoint for influence struggle, where we choose who turn first in that phase

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#110]
- [ ] as query
- [ ] check has_priority on back, if not - raise error (what a error)

#133 

this is in `influence struggle`

**Comment by chemeshuggah** [comment]
1. Added in to player schema after "has_priority":
"has_turn_first": {
            "title": "Priority for briefing phase",
            "type": "boolean"
          },

3. 409 error (Conflict)

**Comment by KonstantinKlepikov** [comment]
`has_turn_priority`
`has_influence_priority`

`has_priority` -> `has_turn_priority`

**Comment by KonstantinKlepikov** [comment]
it is balance setting - is makes in previous phase
