### ISSUE TITLE
delayed Double Agent card ability at the start of the phase and choose agent logic

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#117]
- [x] ~add field to current_game data - is_available_ability~ no we have list of available abilities for players - it is a field `abilities`
- [x] ~if True for bot - set bots agent choice, then reveal this choice to player in current_game data, then set ability to False~
- [x] ~if True for player - player set agent, then bot set agent and nothing else~
- [x] is revealed in any case - ability priority is determine in last phase
- [x] update schema, model and game processor
- [x] determine the agent
- [x] ~check is not dead~
- [x] ~check is not in vacation~
- [x] add hidden representation of agent
- [x] reveal agent
- [x] raise error if player next phase without choosing agent
- [x] remove double ability when next from briefing
- [x] hide agents after move to hand
- [x] vacation -> hand move
- [x] second cheaf play -> hande instead vacation
- [x] ~add endpoint~

**Comment by KonstantinKlepikov** [comment]
needs changes to schema, because information about agents is particle hidden from player, we need representation of data about opponent agents looks like:

agents ->
    dead:  list[str] - ids of dead agents
    in_play: Optional[str] - the id of agent in play or None or spetial word, that signalize - agent in play is hidden
    in_vacation: list[str] - the ids of vacated agents
    in_hand: list[str] - ids of agents or spetial wors if hidden

as spetial word we can use "_hidden"

**Comment by KonstantinKlepikov** [comment]
![Image](https://user-images.githubusercontent.com/20581667/211908147-5cc0b6bd-355c-471f-9095-a2c89355ff34.png)
