### ISSUE TITLE
add game rules in Gdrive

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#12]
add game rules on Gdrive
We need rules for developing/creating interface prototype
[link](https://drive.google.com/file/d/1DWL5Q1WQLXvoT0CD83Ng-wRLFnzaELzS/view?usp=sharing)

**Comment by KonstantinKlepikov** [comment]
it is not completed rules!!!

we need something like that: [fg rules](https://images-cdn.fantasyflightgames.com/filer_public/d7/e5/d7e5c3a6-652b-4d13-be1c-b08b9fb2fbf1/coldwar_rulebook.pdf)

**Comment by chemeshuggah** [comment]
Added rulebook
[link](https://drive.google.com/file/d/1HcI1pBnfL_FSe8OcoqiJXAX5BRsB1IjV/view?usp=sharing)
