### ISSUE TITLE
Frontend: Add interface for who turn first choosing

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#121]
- [ ] If you has priority (for api look at #110):

![Image](https://user-images.githubusercontent.com/110730884/203336209-39472db0-d384-4996-ae33-bd4276e1a8b2.png)

- [ ] if opponent has priority:

![Image](https://user-images.githubusercontent.com/110730884/203336396-1c50276b-a693-4be4-a9af-80787b82391a.png)

**Comment by KonstantinKlepikov** [comment]
on this iteration we make only random choose, because true choose is making in another phase - when we play group sub game
