### ISSUE TITLE
develop functional tests for test interaction user with api

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/cold-war-boardgame#131]
1. Learn `gherkin` specification

    we would be use domain-specific language `gherkin` to describe functional tests. Research articles about this methodology on examples:
    
    - [Behavior Driven Development](https://behave.readthedocs.io/en/stable/philosophy.html#)
    - [What's in a Story?](https://dannorth.net/whats-in-a-story/)
    - [Gherkin: Feature Testing Language](https://behave.readthedocs.io/en/stable/gherkin.html#gherkin-feature-testing-language)
    - [some examples](https://behave.readthedocs.io/en/stable/tutorial.html#tutorial)
    
2. Build functional test scenarios

    In this modeling we need represent behave of user, that use cold-war api and make some right or/and wrong steps. This user send some requests and await some responses - test mus assert right and wrong requests and predictable behave of api on response
    
    We need tests those scenarios:
    
    - authentication
    - create new game
    - ask for data
    - prepare for game (like choosing of priority)
    - switching of  phases and provoked by this data changes
    
    include to test two phases:
    - briefing
    - planing

**Comment by chemeshuggah** [comment]
[link](https://gist.github.com/chemeshuggah/7cf6487eb7a7830e446a081bfe455ded)

**Comment by chemeshuggah** [comment]
Updateв file: (Gherkin API auth test|https://gist.github.com/chemeshuggah/7cf6487eb7a7830e446a081bfe455ded)

**Comment by chemeshuggah** [comment]
need to discuss
[NewGameAPITest](https://gist.github.com/chemeshuggah/245ff49e78e8eabfc847ae4bac6f92f5)
