### ISSUE TITLE
use streamlit capabilities for web app MVP and use figma for prototyping (research)

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#15]
## Discover streamlit for MVP prototyping

- [streamlit app](https://streamlit.io/)
- [examples](https://streamlit.io/gallery)
- [docs](https://docs.streamlit.io/)
- --> WHAT WE CAN DO [streamlit api reference](https://docs.streamlit.io/library/api-reference) <-- use this as source of available components

## Use figma

- register in [web app](https://www.figma.com/) (and you can get desctop app to windows and ubuntu)
- tell me now how connect you to shared prototypes in figma
- find and learn some entry videos about figma-piplines on youtube

**Comment by chemeshuggah** [comment]
Registration and first interaction with figma and streamlit
Created prototype of Reg/Auth and Main menu pages on figma. Link for sharing:
[link](https://www.figma.com/file/zxumCvciBJfMZ08TxcG0p2/ColdWar_pototype?node-id=0%3A1)

**Comment by chemeshuggah** [comment]
Updated prototype with streamlit components. Need review and feedback. Check Main page, Desktop-3

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah call 22.00+
