### ISSUE TITLE
choose rest api engine

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#3]
- [fastapi](https://fastapi.tiangolo.com/)
- [starlit](https://starlite-api.github.io/starlite/)

**Comment by KonstantinKlepikov** [comment]
starlit:

+

- full functionality, like fastapi
- newest open-api specification support 
- oop style

-

- a new solution - no a lot information and guides
- in GET not supported body

for learning: we can use starlit

**Comment by KonstantinKlepikov** [comment]
not many build in solutions for starlite. Switch to use fastapi
