### ISSUE TITLE
Oauth reg/auth - look for solution for strarlite

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#4]
- choose auth vendor
  - [ ] g+
  - [ ] telegram
- pipeline for backend integration

**Comment by KonstantinKlepikov** [comment]
- [JWT authentication for starlite](https://starlite-api.github.io/starlite/usage/8-authentication/)
- no clear solution for oauth
- no needed on this iteration

-> create fixed users in db, use they for MVP
