### ISSUE TITLE
Make real prototype of interface in figma

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#41]
Prototype: [link](https://www.figma.com/file/zxumCvciBJfMZ08TxcG0p2/ColdWar_pototype?node-id=7%3A2)

**Comment by KonstantinKlepikov** [comment]
[brief](https://docs.google.com/document/d/1Fe65af7yqk3LbBSAmZSHQvs3C3BQYg187KWOIIpmfFE/edit?usp=sharing)

- [ ] describe prototype problems to solve
- [ ] decompose to many small tasks
- [ ] create milestone and add tasks with dates to end next week

@chemeshuggah
