### ISSUE TITLE
Need add photos of all objective cards with special ability

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#42]
There is no photo or description of such cards in internet but it's needed to complete prototype

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah  sovsem ohuel

[boardgamegeek](https://boardgamegeek.com/boardgame/24742/cold-war-cia-vs-kgb)

![Image](https://user-images.githubusercontent.com/20581667/186788282-3f7a2be2-d21a-489a-9c4e-242e73e53bc5.png)

**Comment by chemeshuggah** [comment]
Its agent cards. I'm talking about objective cards with special ability. I found 6 in german :)
