### ISSUE TITLE
describe pipeline of development instruments and tools deploy

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#5]

**Comment by KonstantinKlepikov** [comment]
- [ ] project repo
  - [ ] add front and dependencies
  - [ ] add back and dependencies
  - [ ] use different poetry python stack
  - [ ] docker-compose with
    - [ ] front
    - [ ] back
    - [ ] mongoDB
    - [ ] test db
  - [ ] other project files
- [ ] create db on Mongohub
- [ ] create back on heroku
- [ ] create front on heroku or streamlit hub
- [ ] github-action
  - [ ] test back and front on pull request
  - [ ] build back and push to registry (?) or if to small - to docker hub
  - [ ] build front and push to registry
  - [ ] form registry push latest to heroku
- [ ] add repo for game framework
  - [ ] pypi setup and push to pypi
