### ISSUE TITLE
Rework main window in interface prototype

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#57]
- rework prototype so main window visible from the starts
- add visible player/opponent info separation
- add player decision window on main window
- add tooltips for cards
- add badges for special ability cards
- add log
- remove sidebar

**Comment by chemeshuggah** [comment]
Link - [link](https://www.figma.com/file/zxumCvciBJfMZ08TxcG0p2/ColdWar_pototype?node-id=0%3A1)

**Comment by KonstantinKlepikov** [comment]
1. start the game phase, next phase priority choosing
2. in the phase of group manipulation - player with priority choose who act first
3. draw a group and pass buttons -> move
4. spetial ability and groups - available (yet fixed)
5. highlite target attention (pizdec v gondurase)

[link](https://drive.google.com/drive/folders/1BakZ46G-70LFwQR7zsPW-S7kFrVS4wSW)

- [ ] chekbox

**Comment by chemeshuggah** [comment]
Updated prototype
[link](https://www.figma.com/file/zxumCvciBJfMZ08TxcG0p2/ColdWar_pototype?node-id=0%3A1)
