### ISSUE TITLE
API: make functionality for Authentication and authorization.

### ISSUE THREAD

**Issue by chemeshuggah** [KonstantinKlepikov/cold-war-boardgame#62]
API: make functionality for Authentication and authorization.

- [x] list of endponts
- [x] methods
- [x] security scheme
- [x] response: scheme - success
- [x] errors (example:authorization with 401 error "E-mail or/and password is invalid")
  - 403 forbidden
  - 404 wrong resource
  - 500+

more information:

- [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)
- [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401#:~:text=The%20HyperText%20Transfer%20Protocol%20(HTTP,credentials%20for%20the%20requested%20resource.)
- if frontend sending e-mail or/and password that not existing in database then return 401 error
- if frontend sending valid e-mail/password than generate and save token then send him to user for further authentication. Token length: 180
- ~~if frontend sending logout request than delete auth token~~

**Comment by KonstantinKlepikov** [comment]
@chemeshuggah where is result of "make"? :)

**Comment by chemeshuggah** [comment]
api link in stoplight:
[link](https://testoftest.stoplight.io/)
