### ISSUE TITLE
Make game logic specification

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/cold-war-boardgame#63]
- [x] make table of game functions (like a draw a card, shuffle decks, look, search, etc)
- [ ] discuss

**Comment by chemeshuggah** [comment]
Link to document
[link](https://docs.google.com/spreadsheets/d/1RMlqDq6dWpPCjrnyks-lWx_BBsidatj1PVBPl6aLB7c/edit?usp=sharing)
