### ISSUE TITLE
get the data of cards for adding to db

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/cold-war-boardgame#74]
Add constants to db:

- [x] 21 objective cards in Objective deck
- [x] 24 group cards in Group deck
- [x] 6 CIA agent in CIA HQ
- [x] 6 KGD agent in KGB HQ

@chemeshuggah 

- add data of cards and other objects, represented in .yaml format

**Comment by chemeshuggah** [comment]
First version of data in yaml format: [link](https://drive.google.com/drive/folders/1KzfI1fgSCRD_8XIRCKqr20uUgCuVWLO3?usp=share_link)

**Comment by KonstantinKlepikov** [comment]
[converted.yaml](https://github.com/KonstantinKlepikov/cold-war-boardgame/blob/cards-data/research/converted.yaml)
